### ISSUE TITLE
Startup the Project Base

### ISSUE THREAD

**Issue by aragaosousabr** [aragaosousabr/JSONWebViewer#1]
- This issue is the initial step in the project's development. It focuses on setting up the foundational structure of the JS Vanilla JSON web viewer. To kickstart the project, we need to accomplish the following tasks:
    
    1.  **Environment Setup:**
        
        - Configure a development environment, which includes setting up a code editor, version control system (e.g., Git), and a basic project structure.
    2.  **HTML Structure:**
        
        - Create the HTML structure for the web viewer. Design the layout, including the sections for loading a JSON file, displaying JSON data, and navigation controls.
    3.  **CSS Styling:**
        
        - Apply basic styling to ensure a visually appealing and user-friendly interface. Focus on responsive design to support various screen sizes.
    4.  **JS Functionality:**
        
        - Implement the core functionality of the web viewer.
            - Enable users to load JSON files.
            - Parse and display JSON data.
            - Implement features like pagination or lazy loading for handling large JSON files efficiently.
    5.  **Testing:**
        
        - Conduct initial testing to ensure that the basic functionality works as expected.
    6.  **Documentation:**
        
        - Begin documenting the project, including setting up a README file with instructions for usage and development.

**Progress Criteria:**

- Successful completion of this issue will result in a functional base for the JS Vanilla JSON web viewer. The viewer should be capable of loading and displaying JSON data.

**Comment by RuanAragao** [comment]
Assign to me, pls.
